/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_geoprocessing_model_swmm_JSWMM */

#ifndef _Included_com_geoprocessing_model_swmm_JSWMM
#define _Included_com_geoprocessing_model_swmm_JSWMM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_geoprocessing_model_swmm_JSWMM
 * Method:    run
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_geoprocessing_model_swmm_JSWMM_run
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_geoprocessing_model_swmm_JSWMM
 * Method:    open
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_geoprocessing_model_swmm_JSWMM_open
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_geoprocessing_model_swmm_JSWMM
 * Method:    start
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_geoprocessing_model_swmm_JSWMM_start
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_geoprocessing_model_swmm_JSWMM
 * Method:    step
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_geoprocessing_model_swmm_JSWMM_step
  (JNIEnv *, jobject);

/*
 * Class:     com_geoprocessing_model_swmm_JSWMM
 * Method:    end
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_geoprocessing_model_swmm_JSWMM_end
  (JNIEnv *, jobject);

/*
 * Class:     com_geoprocessing_model_swmm_JSWMM
 * Method:    report
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_geoprocessing_model_swmm_JSWMM_report
  (JNIEnv *, jobject);

/*
 * Class:     com_geoprocessing_model_swmm_JSWMM
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_geoprocessing_model_swmm_JSWMM_close
  (JNIEnv *, jobject);

/*
 * Class:     com_geoprocessing_model_swmm_JSWMM
 * Method:    getSemVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_geoprocessing_model_swmm_JSWMM_getSemVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_geoprocessing_model_swmm_JSWMM
 * Method:    getError
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_geoprocessing_model_swmm_JSWMM_getError
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_geoprocessing_model_swmm_JSWMM
 * Method:    getWarnings
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_geoprocessing_model_swmm_JSWMM_getWarnings
  (JNIEnv *, jobject);

/*
 * Class:     com_geoprocessing_model_swmm_JSWMM
 * Method:    getSimulationDateTime
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_geoprocessing_model_swmm_JSWMM_getSimulationDateTime
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_geoprocessing_model_swmm_JSWMM
 * Method:    findObjectIndex
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_geoprocessing_model_swmm_JSWMM_findObjectIndex
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_geoprocessing_model_swmm_JSWMM
 * Method:    countObjects
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_geoprocessing_model_swmm_JSWMM_countObjects
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_geoprocessing_model_swmm_JSWMM
 * Method:    getObjectId
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_geoprocessing_model_swmm_JSWMM_getObjectId
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_geoprocessing_model_swmm_JSWMM
 * Method:    getNodeParam
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_com_geoprocessing_model_swmm_JSWMM_getNodeParam
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_geoprocessing_model_swmm_JSWMM
 * Method:    getLinkParam
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_com_geoprocessing_model_swmm_JSWMM_getLinkParam
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_geoprocessing_model_swmm_JSWMM
 * Method:    getGagePrecip
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_geoprocessing_model_swmm_JSWMM_getGagePrecip
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_geoprocessing_model_swmm_JSWMM
 * Method:    setGagePrecip
 * Signature: (ID)I
 */
JNIEXPORT jint JNICALL Java_com_geoprocessing_model_swmm_JSWMM_setGagePrecip
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     com_geoprocessing_model_swmm_JSWMM
 * Method:    getSubcatchResult
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_com_geoprocessing_model_swmm_JSWMM_getSubcatchResult
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_geoprocessing_model_swmm_JSWMM
 * Method:    getLinkResult
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_com_geoprocessing_model_swmm_JSWMM_getLinkResult
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_geoprocessing_model_swmm_JSWMM
 * Method:    getNodeResult
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_com_geoprocessing_model_swmm_JSWMM_getNodeResult
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
